#pragma once

////////////////////////////////////////////////////////////////
// Current target includes.
////////////////////////////////////////////////////////////////

#include "cppql-typed/fwd.h"
#include "cppql-typed/join.h"
#include "cppql-typed/join_type.h"
#include "cppql-typed/typed_table.h"
#include "cppql-typed/aggregates/average_aggregate.h"
#include "cppql-typed/aggregates/count_aggregate.h"
#include "cppql-typed/aggregates/max_aggregate.h"
#include "cppql-typed/aggregates/min_aggregate.h"
#include "cppql-typed/aggregates/sum_aggregate.h"
#include "cppql-typed/aggregates/total_aggregate.h"
#include "cppql-typed/clauses/columns.h"
#include "cppql-typed/clauses/limit.h"
#include "cppql-typed/clauses/on.h"
#include "cppql-typed/clauses/order_by.h"
#include "cppql-typed/clauses/union.h"
#include "cppql-typed/clauses/using.h"
#include "cppql-typed/clauses/where.h"
#include "cppql-typed/expressions/aggregate_expression.h"
#include "cppql-typed/expressions/column_comparison_expression.h"
#include "cppql-typed/expressions/column_expression.h"
#include "cppql-typed/expressions/comparison_expression.h"
#include "cppql-typed/expressions/filter_expression.h"
#include "cppql-typed/expressions/like_expression.h"
#include "cppql-typed/expressions/logical_expression.h"
#include "cppql-typed/expressions/order_by_expression.h"
#include "cppql-typed/queries/count_query.h"
#include "cppql-typed/queries/delete_query.h"
#include "cppql-typed/queries/insert_query.h"
#include "cppql-typed/queries/select_query.h"
#include "cppql-typed/queries/update_query.h"
#include "cppql-typed/statements/count_statement.h"
#include "cppql-typed/statements/delete_statement.h"
#include "cppql-typed/statements/insert_statement.h"
#include "cppql-typed/statements/select_statement.h"
#include "cppql-typed/statements/select_one_statement.h"
#include "cppql-typed/statements/update_statement.h"
