#pragma once

////////////////////////////////////////////////////////////////
// Current target includes.
////////////////////////////////////////////////////////////////

#include "cppql/aggregates/average_aggregate.h"
#include "cppql/aggregates/count_aggregate.h"
#include "cppql/aggregates/max_aggregate.h"
#include "cppql/aggregates/min_aggregate.h"
#include "cppql/aggregates/sum_aggregate.h"
#include "cppql/aggregates/total_aggregate.h"
#include "cppql/clauses/columns.h"
#include "cppql/clauses/fwd.h"
#include "cppql/clauses/group_by.h"
#include "cppql/clauses/having.h"
#include "cppql/clauses/limit.h"
#include "cppql/clauses/on.h"
#include "cppql/clauses/order_by.h"
#include "cppql/clauses/union.h"
#include "cppql/clauses/using.h"
#include "cppql/clauses/where.h"
#include "cppql/core/binding.h"
#include "cppql/core/column.h"
#include "cppql/core/database.h"
#include "cppql/core/statement.h"
#include "cppql/core/table.h"
#include "cppql/error/cppql_error.h"
#include "cppql/error/sqlite_error.h"
#include "cppql/expressions/aggregate_expression.h"
#include "cppql/expressions/column_comparison_expression.h"
#include "cppql/expressions/column_expression.h"
#include "cppql/expressions/comparison_expression.h"
#include "cppql/expressions/filter_expression.h"
#include "cppql/expressions/like_expression.h"
#include "cppql/expressions/logical_expression.h"
#include "cppql/expressions/order_by_expression.h"
#include "cppql/queries/count_query.h"
#include "cppql/queries/delete_query.h"
#include "cppql/queries/insert_query.h"
#include "cppql/queries/select_query.h"
#include "cppql/queries/update_query.h"
#include "cppql/statements/count_statement.h"
#include "cppql/statements/delete_statement.h"
#include "cppql/statements/insert_statement.h"
#include "cppql/statements/select_statement.h"
#include "cppql/statements/select_one_statement.h"
#include "cppql/statements/update_statement.h"
#include "cppql/typed/fwd.h"
#include "cppql/typed/join.h"
#include "cppql/typed/join_type.h"
#include "cppql/typed/typed_table.h"
